POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer <your_token_here>

{
  "title": "Blog for Deletion Test",
  "author": "Test User",
  "url": "http://testblog.com",
  "likes": 1
}