POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVtaXJ5bmNyIiwiaWQiOiI2ODcyYWFlODQxNDU0ZDcyODk0NDc3M2IiLCJpYXQiOjE3NTIzOTkyNDF9.ATu-dMJq3MgyipsZVL-ry_yItxVWL2xSZOG44o9dPwY

{
    "title": "Token test blog",
    "author": "Test Author",
    "url": "http://added-url.com",
    "likes": 1
}